[package]
name = "hello_world"
version = "0.1.0"
authors = ["sergi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "^0.2.5"
rand = "0.7.2"

